---
title: "Figure-2a"
author: "Mac Campbell"
date: "June 14, 2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)
```

```{r}

library(tidyverse)
library(RcppCNPy)
library(viridis)
library(ggpubr)
library(ggrepel)
library(gridExtra)
library(grid)
```



We need a PCA, this we have already done in 100.   

## PCA with kin removed

```{r}
meta<-read_csv("meta/rd-kin-removed-meta.csv")
covk<-read_delim("outputs/100/RD_all-kinremoved.cov", col_names=FALSE, delim=" ") %>% as.matrix()
```

Function:      
```{r}
#' @param samples character vector with the individuals IDs in the order in which
#' they were passed in the bamlist to angsd.
#' @param cov covariance matrix
covar2pcs <- function(samples, cov) {
  
  
  eig <- eigen(cov, symm = TRUE)
  PC <- as.data.frame(eig$vectors) %>%
    as_tibble() %>%
    setNames(sprintf("PC-%02d", 1:ncol(.)))
  
  samtib <- tibble(sample = samples)
  
  list(
    PCs = bind_cols(samtib, PC),
    eigevalues = eig$values
  )
}
```


```{r}
pcak <- covar2pcs(meta$Label, covk)

pca_longk <- pcak$PCs %>%
  tidyr::gather(., key = "PC", "val", -sample)

# then expand a grid of the possible comparisons (ordered)
expgk <- expand.grid(sample = pcak$PCs$sample,
                    PCx = sprintf("PC-%02d", 1:6),
                    PCy = sprintf("PC-%02d", 1:6),
                    stringsAsFactors = FALSE) %>%
  tibble::as_tibble()

# then left join the pca results onto that
pca_pairsk <- dplyr::left_join(expgk, pca_longk, by = c("sample", "PCx" = "PC")) %>%
  dplyr::rename(val_x = val) %>%
  dplyr::left_join(pca_longk, by = c("sample", "PCy" = "PC")) %>%
  dplyr::rename(val_y = val)

npc <- 3
pck <- pca_pairsk %>%
  filter( (PCx %in% sprintf("PC-%02d", 1:npc)) & 
            (PCy %in% sprintf("PC-%02d", 1:npc)) ) %>%
  left_join(., meta, by = c("sample" = "Label")) %>%
  mutate(group = Locality) 

eigk <- eigen(covk, symm = TRUE)
vark <-eigk$values/sum(eigk$values)
cumvark <-cumsum(eigk$values)/sum(eigk$values)

head(vark)
head(cumvark)

pc12k<-pck %>% filter( (PCx =="PC-01") & (PCy =="PC-02") )
centers12k<-pc12k %>% group_by(Locality) %>% mutate(MeanX=mean(val_x), MeanY=mean(val_y)) %>% select(Locality, MeanX, MeanY) %>% unique()


k12<-ggplot(pc12k, aes(x=val_x, y=val_y, color=Locality))+
  geom_point(size=2, alpha=0.75)+
  geom_text_repel(data=centers12k, aes(x=MeanX, y=MeanY, label=Locality), color="black", fontface='bold', size=2)+
  theme_bw()+
  theme(panel.grid=element_blank())+
  xlab(paste("PC1", " ", round((100*vark[1]),2), "%", sep = ""))+
  ylab(paste("PC2", " ", round((100*vark[2]),2), "%", sep = ""))+
  theme(legend.position = "")+
  ggtitle("Related Individuals Excluded PCs 1 & 2")+
  theme(plot.title = element_text(hjust = 0.5))



pc13k<-pck %>% filter( (PCx =="PC-01") & (PCy =="PC-03") )
centers13k<-pc13k %>% group_by(Locality) %>% mutate(MeanX=mean(val_x), MeanY=mean(val_y)) %>% select(Locality, MeanX, MeanY) %>% unique()

k13<-ggplot(pc13k, aes(x=val_x, y=val_y, color=Locality))+
  geom_point(size=2, alpha=0.75)+
  geom_text_repel(data=centers13k, aes(x=MeanX, y=MeanY, label=Locality), color="black", fontface='bold', size=2)+
  theme_bw()+
  theme(panel.grid=element_blank())+
  xlab(paste("PC1", " ", round((100*vark[1]),2), "%", sep = ""))+
  ylab(paste("PC2", " ", round((100*vark[3]),2), "%", sep = ""))+
  theme(legend.position = "")+
  ggtitle("Related Individuals Excluded PCs 1 & 3")+
  scale_y_reverse()+
  theme(plot.title = element_text(hjust = 0.5))


ggarrange(k12, k13, ncol = 2)

```

Now for panel a:
```{r}
plot12<-ggplot(pc12k, aes(x=val_x, y=val_y, fill=`Geographic Region`, color=`Geographic Region`))+
  scale_color_manual(values=c("blue","green","red")) +
  scale_fill_manual(values=c("blue","green","red")) +
  geom_point(size=2, alpha=0.75, pch=21)+
 # geom_text_repel(data=centers12k, aes(x=MeanX, y=MeanY, label=Locality), color="black", fontface='bold', size=2)+
  theme_bw()+
  theme(panel.grid=element_blank())+
  xlab(paste("\n","PC1", " (", round((100*vark[1]),2), "%)", sep = ""))+
  ylab(paste("PC2", " (", round((100*vark[2]),2), "%)","\n", sep = ""))+
  theme(legend.position = "")+
  #ggtitle("Related Individuals Excluded PCs 1 & 2")+
  theme(plot.title = element_text(hjust = 0.5))

plot12
```

```{r}
plot13<-ggplot(pc13k, aes(x=val_x, y=val_y, fill=`Geographic Region`, color=`Geographic Region`))+
  scale_color_manual(values=c("blue","green","red")) +
  scale_fill_manual(values=c("blue","green","red")) +
  geom_point(size=2, alpha=0.75, pch=21)+
 # geom_text_repel(data=centers12k, aes(x=MeanX, y=MeanY, label=Locality), color="black", fontface='bold', size=2)+
  theme_bw()+
  theme(panel.grid=element_blank())+
  xlab(paste("\n","PC1", " (", round((100*vark[1]),2), "%)", sep = ""))+
  ylab(paste("PC3", " (", round((100*vark[3]),2), "%)","\n", sep = ""))+
  theme(legend.position = "")+
  #ggtitle("Related Individuals Excluded PCs 1 & 2")+
  theme(plot.title = element_text(hjust = 0.5))

plot13
```

```{r}
fig2a<-ggarrange(plot12, plot13, ncol=1)
fig2a
```
```{r}
ggsave("outputs/200/fig2a.pdf", width=6, height=10)
save(fig2a,file="outputs/200/fig2a.rda")
```