---
title: "500-supplemental-figure-S1"
author: "Mac Campbell"
date: "6/21/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)
```

```{r}
library(tidyverse)
library(RcppCNPy)
```

## Optimal K of Range-Wide Dataset
It is 16.
```{r}
k16<-npyLoad("outputs/202/RD_all_glh-bestk.admix.Q.npy") %>% as_tibble() 
#Need to rename all colnames smartly!
colnames(k16)<-gsub("V","Q",colnames(k16))

meta<-read_csv("meta/rd-kin-removed-meta.csv")
meta$`Collection Locality`<-gsub("RD6","",meta$`Collection Locality`)
meta$Locality<-gsub("RD6","",meta$Locality)
order<-c("GSJS","GSTS","SPKR","SPSH","STMR","STPR_BT2","STPR_FT1","STRT","STWA","BTOC","BTQP","RBFL","RBFR","P226","P246")
meta$`Collection Locality`<-factor(meta$`Collection Locality`, levels=order)
s16<-bind_cols(meta,k16) %>% arrange(`Collection Locality`,Locality, Individual) %>% mutate(Index=1:n()) %>% dplyr::select(Label, Index, Locality, `Collection Locality`, Individual, gsub("V","Q",colnames(k16))) %>% gather(key=Ancestry, value=Q, 6:21)

s16$Ancestry<-factor(s16$Ancestry, levels=gsub("V","Q",colnames(k16)))
```

```{r}
labels<-s16  %>% group_by(`Locality`) %>% mutate(Start=min(Index), Stop=max(Index)) %>% 
  select(`Locality`,Start,Stop) %>% unique() %>% 
  mutate(Position=round((Start+Stop)/2))
```

```{r}
s1<-ggplot(s16) + 
  geom_col(aes(x=Index, y=Q, fill=Ancestry), color="NA", size = 0, width = 1)+
  geom_segment(data=labels, x = labels$Start - 0.5, y=0, xend = labels$Start-0.5, yend=1, alpha=0.9, size=0.25) +
  geom_segment(data=labels, x = labels$Stop[length(labels$Stop)]  + 0.5, y=0, xend=labels$Stop[length(labels$Stop)] + 0.5, yend=1,  alpha=0.9,
               size=0.25) +
  geom_segment(x=0, xend=labels$Stop[length(labels$Stop)], y=1, yend=1, alpha=0.9, size=0.25) +
  geom_segment(x=0, xend=labels$Stop[length(labels$Stop)], y=0, yend=-0.0, alpha=0.9, size=0.25) +
  theme_bw() + 
  theme(panel.grid = element_blank()) +
  scale_fill_viridis_d(option="plasma") +
  ylim(-0.001,1.01) +
  xlim(-0.1, labels$Stop[length(labels$Stop)]+1) +
  scale_x_continuous(breaks=labels$Position, labels=labels$`Locality`) +
  theme(axis.text.x = element_text(angle=45, hjust=1)) +
  xlab("") +
  ylab("Q\n") +
  theme(axis.title.y=element_text(size=14, face="bold")) +
  theme(axis.text.y = element_text(size=12)) +
  ggtitle("K = 16") +
  theme(plot.title = element_text(size=16, face="bold", hjust=0.5))

s1
ggsave("outputs/500/supplemental-figure-s1.jpg", width=16, height=8)
ggsave("outputs/500/supplemental-figure-s1.pdf", width=16, height=8)

```

Get Colors:
```{r}
cols<-scales::viridis_pal(option = "plasma")(length(levels(s16$Ancestry)))
coldf<-bind_cols(cols, levels(s16$Ancestry)) %>% mutate(Q=1:n())
coldf
ggplot(coldf, aes(x=Q, y=Q))  +
  geom_point(color=coldf$...1, size=10) +
  geom_text(aes(x=Q, y=Q, label=...2)) +
  theme_bw()
```

Summarize all.
```{r}
tidy<-s16 %>% select(`Collection Locality`, Locality, Ancestry, Q, Index) %>%  group_by(`Collection Locality`, Locality, Ancestry) %>% summarise_all(list(mean)) %>%
  mutate(Count=n()) %>% left_join(coldf %>% select(-Q), by=c("Ancestry"="...2"))
save(tidy, file="outputs/500/colors-s1.rda")
```

```{r}
ggplot(tidy) +
    geom_col(aes(x=Index, y=Q, fill=Ancestry), color="NA", size = 0) +
    scale_fill_viridis_d(option="plasma") +
    theme(axis.text.x = element_text(angle=45, hjust=1)) +
    scale_x_continuous(breaks=labels$Position, labels=labels$`Locality`) +
  theme(axis.text.x = element_text(angle=45, hjust=1)) 
```

