---
title: "600-supplemental-figure-S2"
author: "Mac Campbell"
date: "6/21/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)
```

```{r}
library(tidyverse)
library(ggpubr)
library(RcppCNPy)
library(ggpubr)
library(gridExtra)
```

## Supplemental Figure S2
This is of multiple Ks in the western valleys, K in 2..6?

Generate Ks.

```{sh, eval=FALSE}
for i in {2..6};
  do echo $i; 

  python $HOME/pcangsd/pcangsd.py -beagle /home/abenj93/projects/RelictDace/data/de_novo/RD_popgen/results_admix/BT.RB_admix/RD_BT.RB_glh.beagle.gz \
-relate outputs/300/RD_BT.RB.kinship.kinship.npy  -admix -admix_K $i -o outputs/600/RD_BT.RB_glh-k$i -threads 5 ;

done;
```

Get this local.

### Need meta

```{r}
data<-read_tsv("meta/location-codes.tsv") %>% rename(Label=label)

bams<-read_tsv("bamlists/RD_BT.RB.bamlist", col_names = c("Path"))
bams$Bam<-gsub("/home/abenj93/projects/RelictDace/data/de_novo/RD_alignment/RAD_align/","",bams$Path)
bams$Bam<-gsub("_R1.sort.proper.rmdup.bam","",bams$Bam)
bams$Label<-bams$Bam

meta<-bams %>% select(-Path, -Bam) %>% left_join(data)  %>% mutate(Individual=1:n()) %>% rename(Site=Locality)

excl<-npyLoad("outputs/300/RD_BT.RB-kinremoved.unrelated.npy") %>% as_tibble()
kept<-meta$Individual[excl$value!=0]
meta<-filter(meta, Individual %in% kept)
```

```{r}
PlotPCAdmix<- function(file) {
  
q<-npyLoad(file) %>% as_tibble() 
#Make generic colnames

colnames(q)<-gsub("V","Q",colnames(q))

qs<-length(colnames(q))
#Arrange Sites

r<-bind_cols(meta,q) %>% arrange(Site) %>% mutate(Index=1:n())

r$Site<-factor(r$Site, levels=unique(r$Site))

rdf<-r %>% select(Site, Index,  colnames(q) ) %>% gather(key=Ancestry, value=Q, 3:(3+length(colnames(q))-1))

#Make names for structure-like plot
labels<-rdf  %>% group_by(Site) %>% mutate(Start=min(Index), Stop=max(Index)) %>% 
  select(Site,Start,Stop) %>% unique() %>% 
  mutate(Position=round((Start+Stop)/2))

#Plot
plot<-ggplot(rdf) + 
  geom_col(aes(x=Index,y=Q, fill=Ancestry), color="NA", size = 0, width = 1)+
  geom_segment(data=labels, x = labels$Start - 0.5, y=0, xend = labels$Start-0.5, yend=1, alpha=0.9, size=0.25) +
  geom_segment(data=labels, x = labels$Stop[length(labels$Stop)]  + 0.5, y=0, xend=labels$Stop[length(labels$Stop)] + 0.5, yend=1,  alpha=0.9,
               size=0.25) +
  geom_segment(x=0, xend=labels$Stop[length(labels$Stop)], y=1, yend=1, alpha=0.9, size=0.25) +
  geom_segment(x=0, xend=labels$Stop[length(labels$Stop)], y=0, yend=-0.0, alpha=0.9, size=0.25) +
  theme_bw() + 
  theme(panel.grid = element_blank()) +
  scale_fill_viridis_d(option="inferno") +
  ylim(-0.001,1.01) +
  xlim(-0.1, labels$Stop[length(labels$Stop)]+1) +
  scale_x_continuous(breaks=labels$Position, labels=labels$Site) +
  theme(axis.text.x = element_text(angle=45, hjust=1)) +
  xlab("") +
  ggtitle(paste0("K = ", qs)) +
  theme(plot.title = element_text(hjust=0.5, face="bold"))

ggsave(paste0("outputs/600/pcangsd-admix-",qs,".jpg"), width=12, height=8)
ggsave(paste0("outputs/600/pcangsd-admix-",qs,".pdf"), width=12, height=8)
return(plot)
}
```

```{r}
files<-list.files("outputs/600/", pattern="admix.Q.npy", full.names = TRUE)
plots<-lapply(files, PlotPCAdmix)
```

Combine, I can use pdfjam.   

```{sh, eval=FALSE}
pdfjam outputs/600/*admix*.pdf --nup 1x5 --outfile outputs/600/Supplemental\ Figure\ S2.pdf
```

Hmm, I don't like this. Trying something else.

```{r}
jpeg(filename = "outputs/600/Supplemental Figure S2.jpeg",width=12, height=16, units = "in", res = 300)

grid.arrange(grobs=plots, ncol=1)

dev.off()
```

